disabled_rules:
    - trailing_whitespace
    - identifier_name
    - line_length
    - type_name
    - vertical_whitespace

opt_in_rules:
    - empty_count
    - empty_string

included:
    - pre-capstone
excluded:
    - pre-capstone/Application/AppDelegate.swift
    - pre-capstone/Application/SceneDelegate.swift


force_cast: warning
